#!/bin/bash

set -e

if [ "$1" = "staging" ]; then
    BUCKET="s3://vit-configurator-staging.votinginfoproject.org/"
elif [ "$1" = "prod" ]; then
    BUCKET="s3://vit-configurator-production.votinginfoproject.org/"
else
    echo "Usage: $0 [staging|prod]"
    exit 1
fi

aws s3 sync --delete target/output/public "$BUCKET"
